### ISSUE TITLE
monitoring needs

### ISSUE THREAD

**Issue by rafipiccolo** [mcuadros/ofelia#100]
Hello,

I use daemon --docker to run ofelia.

Now that everything works I try to implement a monitoring server on it. (influxdb + grafana)
I can provide an exemple of configuration if you want.

I want to send the following data for each job to influxdb to create graphs and alerts : jobname, date, duration, result(failed / not failed), output

Here comes the problem, I cannot run docker and config.ini alltogether :
When is use this command, only docker labels are executed, slack / save directory is ignored :

        daemon --docker --config=/etc/ofelia/config.ini

When is use this, slack is working, but ofc no docker parsing :

        daemon --config=/etc/ofelia/config.ini

here is my config.ini
```
[global]

save-folder=/data
save-only-on-error=false

slack-webhook=http://slack:3000/shit
slack-only-on-error=false

[job-local "job-executed-on-current-host"]
schedule = @every 5s
command = echo raf && echo raf && echo raf
```

If you dont plan to resolve this bug, Is there an alternative ?

- would it be possible to have a influxdb exporter ? its as easy as posting this kind of string to a url : "dbname,label=value field=value,field=value timestamp"

Example :
curl -i -X POST 'http://localhost:8086/write?db=mydb&u=root&p=superpassword' --data-binary 'ofelia,job=echotest duration=64000,failed=0,error=0 1582032137924'

- If not, would it be possible to have only a json stream on stdout ?

- if not, would it be possible to have a json pushed to a custom url ?

Thanks.

**Comment by Trane9991** [comment]
@rafipiccolo I'm not completely sure that it would work as expected since I didn't test it myself, however, it should be possible to provide slack/save configurations via labels as well.

So if we take docker-compose example from [README.md](https://github.com/mcuadros/ofelia#docker-labels-configurations) you should be able to do next:

```yaml
version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nginx
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.save-folder: "/data"
      ofelia.save-only-on-error: "false"
      ofelia.slack-webhook: "http://slack:3000/shit"
      ofelia.slack-only-on-error: "false"
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "date"
```

could you please try it out and let me know if that works? if not, I can take a look. You should be able to provide all of the configurations supported in the `.ini` file via docker labels.
