### ISSUE TITLE
Managing containers with job-local  when running Ofelia as a container

### ISSUE THREAD

**Issue by rensa** [mcuadros/ofelia#102]
Hi there,

I'm running Ofelia alongside a few containers,  and I'd like to set up something akin to a "reboot on healthcheck fail" mechanism. Essentially, I periodically check for the presence of a file on my shared volume; if it's there, restart the container.

The problem is that I'm running Ofelia as a container, not as a daemon on the host., and as the docs note:

> **Note:** In case Ofelia is running inside a container, the command is executed inside the container. Not on the Docker host.

Here's my existing `docker-compose.yml`:

```
services:

  # [other services]

  ofelia:
      image: mcuadros/ofelia:latest
      command: daemon --docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /datasets:/datasets
      labels:
        # logging
        ofelia.save-folder: "/ofelia-logs"
        # [other scheduled jobs]
        # restart climdex-api when /datasets/ghcndex-updated appears
        ofelia.job-local.dirtycatalogue.schedule: "@every 10m"
        ofelia.job-local.dirtycatalogue.command: 'if [ -f "/datasets/ghcndex_updated" ]; then docker restart climdex-api; fi'
```

I'd hoped that if the container has access to the docer socket, it would still be able to run docker commands that would reach the other containers. But if I shell into it, it's clearly not as simple as just running docker commands as usual. Can I modify this to conditionally restart the container (even if `job-local` isn't the tool for the job)?
