### ISSUE TITLE
Stdout/stderr log files are empty

### ISSUE THREAD

**Issue by rensa** [mcuadros/ofelia#103]
I have a service scheduled to run. If I run the container manually, it runs fine and produces output as it runs. But when it's scheduled, it fails after a minute - and when I go to check the log files inside my Ofelia container, the stdout/stderr log files are present but empty:

```
/var/log # ls -hl
[...]
-rw-r--r--    1 root     root           0 Jun 11 04:37 20200611_043743_ghcndexcheck.stderr.log
-rw-r--r--    1 root     root           0 Jun 11 04:37 20200611_043743_ghcndexcheck.stdout.log
-rw-r--r--    1 root     root         738 Jun 11 04:42 20200611_044243_ghcndexcheck.json
-rw-r--r--    1 root     root           0 Jun 11 04:42 20200611_044243_ghcndexcheck.stderr.log
-rw-r--r--    1 root     root           0 Jun 11 04:42 20200611_044243_ghcndexcheck.stdout.log
-rw-r--r--    1 root     root         739 Jun 11 04:55 20200611_045418_ghcndexcheck.json
-rw-r--r--    1 root     root           0 Jun 11 04:55 20200611_045418_ghcndexcheck.stderr.log
-rw-r--r--    1 root     root           0 Jun 11 04:55 20200611_045418_ghcndexcheck.stdout.log
-rw-r--r--    1 root     root         739 Jun 11 05:00 20200611_045918_ghcndexcheck.json
-rw-r--r--    1 root     root           0 Jun 11 05:00 20200611_045918_ghcndexcheck.stderr.log
-rw-r--r--    1 root     root           0 Jun 11 05:00 20200611_045918_ghcndexcheck.stdout.log
```
Is this a problem with my Ofelia specification, or a problem with Ofelia? Here's part of my `docker-compose.yml`:

```
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia_container
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /datasets:/datasets
    labels:
      # logging: save inside the container if there's an error
      # (turn that off if you need to debug when there's no error)
      ofelia.save-folder: /var/log
      ofelia.save-only-on-error: true
      # run catalogue-ghcndex four times a day (unless it's still running)
      # ofelia.job-run.ghcndexcheck.schedule: "0 0 * * *"
      ofelia.job-run.ghcndexcheck.schedule: "@every 5m"
      ofelia.job-run.ghcndexcheck.image: "catalogue-ghcndex"
      ofelia.job-run.ghcndexcheck.no-overlap: "true"
      ofelia.job-run.ghcndexcheck.save-folder: /var/log
      ofelia.job-run.ghcndexcheck.save-only-on-error: false
```

I've also tried removing the logging line specific to this `ghcndexcheck` job and just having the global ones at the top (with `save-only-on-error` set to `false`). Same result.
