### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by helmut72** [mcuadros/ofelia#107]
First, a great project. I've tried docker-compose.yml example with Nginx only. Memory usage rised to over 6MB, just for running 'uname -a' over the night.

A cron daemon takes about 1.5MB for running the same script.

Update: now use 10MB and still runs 'uname -a' in the Nginx container only.

Update2: now use 15.5MB RAM after 2 days, still runs just 'uname -a' in the Nginx container without 'date' in Ofelia container - the example in your readme

Update3: now nearly at 20MB RAM usage and removed the Container.

**Comment by sillycube** [comment]
Yes, I found the same issue when I used Ofelia to send email sequence to my users. The docker consumed 400mb just to load users from db and sent emails to sendgrid.

**Comment by beholdr** [comment]
Same here, after couple of months of work ofelia process consumes 400+ Mb instead of 10 Mb in the beginning.

**Comment by Trane9991** [comment]
🤔 interesting. This will need profiling to find out why memory consumption is growing over time.

**Comment by Mazyod** [comment]
This worried me a lot, and after looking at the code, nothing seems like it's storing unnecessary data over time.. So, suspecting logging issues I created this demo:

```yaml
version: "3.8"

services:
  ofelia:
    image: mcuadros/ofelia
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 1s"
      ofelia.job-local.my-test-job.command: "cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32000 | head -n 1"
```

Running:
https://asciinema.org/a/Tnn6hsI7zhvLRDA8MZx42xnGm
