### ISSUE TITLE
Issue pulling from Private Repository

### ISSUE THREAD

**Issue by Mythirion** [mcuadros/ofelia#118]
Hi,

We're moving over to Ofelia from docker-crontab because we want alerts when the cronjobs don't quite work. Having some trouble at the minute getting Ofelia to work with our private GitLab repository, however.

We have a test job, called foo-bar, for example:
```
[job-run "foo-bar"]
schedule = @every 5m
image = private-gitlab-repo-image:image_sha
command = /scripts/testScript.sh
volume = test/ofelia/directory:/mnt/directory
delete = true
pull = true
```

I also have a Dockerfile (added the `docker login` for the private repo):
```
FROM mcuadros/ofelia

RUN apk add docker && docker login -u [deploy-token] -p [password] [repo]
COPY config.ini /etc/ofelia/config.ini
```

And a docker-compose (we use docker-compose in prod. Also mounted my config.json because I read somewhere that you need to add it to work with private repos. Doesn't work without it either):
```
version: '3.6'

services:
  ofelia:
    build: ofelia/
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/log/ofelia:/var/log/crontab
      - /home/user/.docker/config.json:/root/.docker/config.json
```

Then, I'm simply running `docker-compose up --build` to build and run the 'stack'.

I'm getting the error:
```
ofelia_1  | scheduler.go:35 ▶ NOTICE New job registered "foo-bar" - "/scripts/testScript.sh" - "@every 5m"
ofelia_1  | scheduler.go:55 ▶ DEBUG Starting scheduler with 1 job
ofelia_1  | common.go:124 ▶ NOTICE [Job "foo-bar" (18b59c2be7a5)] Started - /scripts/testScript.sh
ofelia_1  | common.go:120 ▶ ERROR [Job "foo-bar" (18b59c2be7a5)] Finished in "1.425492638s", failed: true, skipped: false, error: couldn't find image on the host
```

One would assume from the code that (especially after adding pull = true to the config.ini file) it should try to pull the image first.

How do I fix this?

Thanks
