### ISSUE TITLE
Ofelia container is terminated by the system 

### ISSUE THREAD

**Issue by etienneleba** [mcuadros/ofelia#123]
Hi everyone,

I'm running an ofelia container on a prod server with this config : 

```yaml
# docker-compose.yml

ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - php
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Paris
```

But the container stops after few hours cause of this signal : 

```
ofelia_1      | daemon.go:69 ▶ WARNING Signal received: terminated, shutting down the process
ofelia_1      | daemon.go:83 ▶ WARNING Waiting running jobs.
```
On my test server the ofelia container is receiving the same signal but restart after, but on the prod one, it is not restarting after the signal. Someone has a clue for me ?
