### ISSUE TITLE
No mail on job failure if global settings overridden

### ISSUE THREAD

**Issue by 0xERR0R** [mcuadros/ofelia#124]
Consider following example:
```yaml
version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.smtp-host: "smtp.gmail.com"
      ofelia.smtp-port: "587"
      ofelia.smtp-user: "XXX@googlemail.com"
      ofelia.smtp-password: "XXX"
      ofelia.email-to: "XXX@gmail.com"
      ofelia.email-from: "Ofelia <XXX@gmail.com>"
      ofelia.mail-only-on-error: "false"
      # 
      # This job is alway successful
      ofelia.job-local.job1.schedule: "@every 15s"
      ofelia.job-local.job1.command: "true"
      #
      # This job always fails
      ofelia.job-local.job2.schedule: "@every 15s"
      ofelia.job-local.job2.command: "false"
      #
      # This job always fails
      ofelia.job-local.job3.schedule: "@every 15s"
      ofelia.job-local.job3.command: "false"
      ofelia.job-local.job3.mail-only-on-error: "true"
```

I have 3 jobs. Job 1 is always successful, job 2 and 3 always fail. Global configuration: send always mail (for successful and failed jobs). But for job3, I want to override this behaviour: I want to receive mail only if job3 fails.

This doesn't work, I get: `mail.go:57 ▶ ERROR Mail error: "dial tcp :0: connect: connection refused"`

In my opinion, the global configuration can be overridden (partially) in the job definition. In this case, it looks, like I must also define ALL mail properties (like host, user, password) on the job definition.
