### ISSUE TITLE
Ofelia not picking up Docker label configuration

### ISSUE THREAD

**Issue by marcelbrueckner** [mcuadros/ofelia#126]
Hello,

I set up Ofelia via `docker-compose.yml` to pick up configuration via Docker labels attached to the target containers.
When starting Ofelia (of course after the target container is running) I get `unable to start a empty scheduler.` printed to Ofelia's logs.

### Problem
<details>
  <summary><b>An extract of the target container's `docker-compose.yml`:</b></summary>

```yaml
# Firefly III
# https://docs.firefly-iii.org/installation/docker

---
version: '3.5'

services:
  firefly_iii:
    image: jc5x/firefly-iii:version-5.4.3
    # A static name is easier referenced from Ofelia
    # If used, service cannot be scaled beyond 1 container
    # https://docs.docker.com/compose/compose-file/#container_name
    container_name: firefly_iii
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      ofelia.enable: "true"
      ofelia.job-exec.firefly-iii.schedule: "@hourly"
      ofelia.job-exec.firefly-iii.command: "/usr/local/bin/php /var/www/html/artisan firefly:cron"
      # https://github.com/firefly-iii/firefly-iii/issues/3530
      ofelia.job-exec.firefly-iii.user: "www-data"

...
```
</details>

<details>
  <summary><b>Ofelia `docker-compose.yml`:</b></summary>

```yaml
# Ofelia
# A modern and low footprint job scheduler for docker environments, built on Go. 
# https://github.com/mcuadros/ofelia

---
version: '3.5'

services:
  ofelia:
    # https://www.tikalk.com/posts/2018/05/08/ofelia-cron-tasks-on-steroids-in-docker/
    image: mcuadros/ofelia:latest
    container_name: ofelia
    command: daemon --docker
    volumes:
      # https://docs.docker.com/compose/compose-file/#long-syntax-3
      # Bind Docker socket to be able to 'docker exec' commands
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
        read_only: true
```
</details>

```bash
$ docker logs ofelia
unable to start a empty scheduler.
```

### Workaround

If I use the INI configuration instead it works flawlessly. The job is scheduled and executed without any problems. However, I would like to keep my job configurations as Docker labels.

<details>
  <summary><b>ofelia-config.ini:</b></summary>

```ini
[job-exec "firefly-iii"]
schedule = @hourly
container = firefly_iii
command = /usr/local/bin/php /var/www/html/artisan firefly:cron
user = www-data
```
</details>

<details>
  <summary><b>Ofelia `docker-compose.yml`:</b></summary>

```yaml
# Ofelia
# A modern and low footprint job scheduler for docker environments, built on Go. 
# https://github.com/mcuadros/ofelia

---
version: '3.5'

services:
  ofelia:
    # https://www.tikalk.com/posts/2018/05/08/ofelia-cron-tasks-on-steroids-in-docker/
    image: mcuadros/ofelia:latest
    container_name: ofelia
    command: daemon --config /ofelia-config.ini
    volumes:
      # https://docs.docker.com/compose/compose-file/#long-syntax-3
      # Bind Docker socket to be able to 'docker exec' commands
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
        read_only: true
      - source: ./ofelia-config.ini
        target: /ofelia-config.ini
        type: bind
```
</details>

```bash
$ docker logs ofelia
scheduler.go:35 ▶ NOTICE New job registered "firefly-iii" - "/usr/local/bin/php /var/www/html/artisan firefly:cron" - "@hourly"
scheduler.go:55 ▶ DEBUG Starting scheduler with 1 jobs
common.go:124 ▶ NOTICE [Job "firefly-iii" (652ec17bce5d)] Started - /usr/local/bin/php /var/www/html/artisan firefly:cron
common.go:124 ▶ NOTICE [Job "firefly-iii" (652ec17bce5d)] Output: The recurring transaction cron job fired successfully.
The auto budget cron job fired successfully.
More feedback on the cron jobs can be found in the log files.
common.go:124 ▶ NOTICE [Job "firefly-iii" (652ec17bce5d)] Finished in "1.818081388s", failed: false, skipped: false, error: none
```
