### ISSUE TITLE
Ofelia is not starting my scheduler

### ISSUE THREAD

**Issue by teatonic** [mcuadros/ofelia#134]
**What I'm quite sure :** 
target container has to be started before ofelia because ofelia is depending on it  

**What is not clear**
where to describe the job : in the  "target" container (in my case "postgres") OR in a config.ini ?

**Error** 
```
ofelia_1    | unable to start a empty scheduler.
```

**Here is my config.ini file**
```
[job-exec "postrges_backup"]
schedule = @every 10s
container = postgres_container
command = pg_dump --file=/data/postgres_bckp/payonce_dev/BCKP_payonce_dev_YYYY_mm_JJ_HH_MM_SS.txt --dbname=postgresql://postgres:changeme@postgres:5432/payonce_dev --verbose --format=p
[global]
save-folder = /data/postgres_bckp/payonce_dev
save-only-on-error = false
```

**Here is my docker-compose.yml file**

```
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    labels:
      - 'ofelia.enabled="true"'
    environment:
      - POSTGRES_USER=${PGDB_USER} #Non pris en compte => POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PGDB_PASSWORD} #Non pris en compte => POSTGRES_PASSWORD=changeme
      - PGDATA=/data/postgres
      - POSTGRES_DB=${PGDB_NAME}
    volumes:
       - /data/postgres:/data/postgres
       - /data/postgres_bckp/:/data/postgres_bckp/
    labels:
      - 'ofelia.job-exec.postrges_backup.schedule: @every 5s'
      - 'ofelia.job-exec.postrges_backup.command: pg_dump --file=/data/postgres_bckp/payonce_dev/BCKP_dev_YYYY_mm_JJ_HH_MM_SS.txt --dbname=postgresql://postgres:changeme@postgres:5432/mydb --verbose --format=p'
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - postgres
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/postgres_bckp:/data/postgres_bckp:rw
      - /home/user1/repos/postgres_pgadmin/config.ini:/etc/ofelia/config.ini
    networks:
      - postgres
networks:
  postgres:
    driver: bridge


```
