### ISSUE TITLE
Network mode = host?

### ISSUE THREAD

**Issue by marabesi** [mcuadros/ofelia#144]
Hello there,

How can I set the network mode in the `job-run`?

I would achieve that running the container with the flag network=host, for example:

```
docker run --rm --network=host nginx
```

or in the docker-compose, I would pass in the flag: network_mode, such as:

```
version: "2.2"
services:
  ofelia:
    network_mode: host
    restart: always
    image: mcuadros/ofelia:v0.3.4
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # reseaarch
      ofelia.job-run.reminders-reseaarch.no-overlap: "true"
      ofelia.job-run.reminders-reseaarch.schedule: "@every 30s"
      ofelia.job-run.reminders-reseaarch.image: nginx
      ofelia.job-run.reminders-reseaarch.command: "sleep 30"

```
