### ISSUE TITLE
Docker-Compose Ofelia unable to start an empty scheduler 

### ISSUE THREAD

**Issue by mtetreault** [mcuadros/ofelia#147]
Hello,
I have a project that use docker-compose and some images that are built locally. I have try a multitude of thing and I always come up with the error `Ofelia unable to start a empty scheduler`. I am unsure if this is a bug or simply something I misunderstood.

The parser container is a simple python container that install python requirements and copy the python script to /usr/src/app. The script checks if there is new data in a AWS bucket, if there is it process the data and push it to a database. Once it's done the script exits.

To it's simplest expression the docker-compose goes as follow:
```yml
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - parser
    command: daemon --docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  parser:
    container_name: parser
    build:
      context: dashboard-writer
      dockerfile: Dockerfile
    volumes:
      - ./dashboard-writer:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.datecron.image: "parser"
      ofelia.job-run.datecron.schedule: "@every 30s"
      ofelia.job-run.datecron.command: "python3 /usr/src/app/main.py"
```

**Comment by Trane9991** [comment]
Hey @mtetreault 

you need to use `job-exec` instead of `job-run`.

With `job-exec`, `ofelia` will run command **inside** parser container, and this is what you need as far as I understand.

So something like:

```yml
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - parser
    command: daemon --docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  parser:
    container_name: parser
    build:
      context: dashboard-writer
      dockerfile: Dockerfile
    volumes:
      - ./dashboard-writer:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 30s"
      ofelia.job-exec.datecron.command: "python3 /usr/src/app/main.py"
```

**Comment by mtetreault** [comment]
@Trane9991: I forgot to mentionned that job-exec and job-run gives me the same error.

I am wondering if the issue comes from the build label instead of image.

**Comment by Trane9991** [comment]
Ok, I got the issue.

the problem with `job-exec` that in order to use it, container **must be running**, however, your container exits on start.

Assume the Dockerfile is following:

```dockerfile
FROM python
RUN sleep 30
```

So possible solutions are:

- `job-exec` in this case `tail -f /dev/null` will make sure that container stays up, so ofelia can `exec` into it:
```yml
version: "3"
services:
 ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - parser
    command: daemon --docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
 parser:
    container_name: parser
    build: .
    command: tail -f /dev/null
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 30s"
      ofelia.job-exec.datecron.command: "python3 /usr/src/app/main.py"
```

- `job-run` in this case, docker-compose will ensure that `parase` image is built (and exited), and `job-run` is defined on the ofelia container labels, so it can start new container from `parser` image:
```yml
version: "3"
services:
 ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - parser
    command: daemon --docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.datecron.image: "parser"
      ofelia.job-run.datecron.schedule: "@every 30s"
      ofelia.job-run.datecron.command: "python3 /usr/src/app/main.py"
 parser:
    image: parser 
    build: .
```
