### ISSUE TITLE
How may I use Ofelia inside my Docker file, [NOT docker-compose]

### ISSUE THREAD

**Issue by anansrivastava** [mcuadros/ofelia#148]
I am using it inside a docker-compose, but the issue is my application hosting services [digital ocean] doesn't support docker-compose file just yet. How can I use Ofelia just inside my docker file?

My compose - 
```
version: "3.9"
services:
  web:
    build: .
    container_name: defcon
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"

  scheduler:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.ini:/etc/ofelia/config.ini
    depends_on:
      - web
```

My docker file - 
```
FROM python:3.8.5
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . /app
RUN pip install --upgrade pip
RUN apt-get update -y && apt-get -y upgrade \
 && apt-get install -y --no-install-recommends build-essential gcc libsndfile1
RUN pip install -r requirements.txt
CMD ["gunicorn", "--workers", "3", "--threads", "4", "--timeout", "30", "-b", "0.0.0.0:5000",  "app:gunicorn_app"]
```

I need help modifying my docker file to include ofelia. Thanks.
