### ISSUE TITLE
Jobs execute on the wrong container

### ISSUE THREAD

**Issue by avataru** [mcuadros/ofelia#156]
I have two almost identical projects. When I start the second project Ofelia seems to also run the jobs on the first project.

first project's docker-compose.yml
```
version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - frontend
      - backend
  web:
    image: nginx:stable-alpine
    container_name: web    
    restart: unless-stopped
    tty: true
    [ ... more settings ... ]
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/scheduler:/var/log/scheduler
    labels:
      ofelia.job-exec.myjob.container: "app"
      ofelia.job-exec.myjob.schedule: "@every 1m"
      ofelia.job-exec.myjob.command: "command"
    networks:
      - backend
[ ... more containers ... ]

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
```

second project's docker-compose.yml
```
version: '3'
services:

  second-app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: second-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: second-app
      SERVICE_TAGS: second-dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - second-frontend
      - second-backend
  web:
    image: nginx:stable-alpine
    container_name: second-web    
    restart: unless-stopped
    tty: true
    [ ... more settings ... ]
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - second-web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/scheduler:/var/log/scheduler
    labels:
      ofelia.job-exec.myotherjob.container: "second-app"
      ofelia.job-exec.myotherjob.schedule: "@every 1m"
      ofelia.job-exec.myotherjob.command: "command"
    networks:
      - second-backend
[ ... more containers ... ]

networks:
  second-frontend:
    driver: bridge
  second-backend:
    driver: bridge
```

Docker's log for the first container will look like this:
```
2021-07-08T14:25:28.382871261Z scheduler.go:35 ▶ NOTICE New job registered "myjob" - "command" - "@every 1m"
2021-07-08T14:25:28.383118394Z scheduler.go:55 ▶ DEBUG Starting scheduler with 1 jobs
```

While the second:
```
2021-07-08T14:44:49.606306404Z scheduler.go:35 ▶ NOTICE New job registered "myjob" - "command" - "@every 1m"
2021-07-08T14:44:49.606356396Z scheduler.go:35 ▶ NOTICE New job registered "myotherjob" - "command" - "@every 1m"
2021-07-08T14:44:49.606362133Z scheduler.go:55 ▶ DEBUG Starting scheduler with 2 jobs
```

What do I need to set so this doesn't happen and each Ofelia container is only concerned about their project?

Thank you
