### ISSUE TITLE
high memory usage (still)

### ISSUE THREAD

**Issue by slinstaedt** [mcuadros/ofelia#157]
The problem with high RAM usage over time mentioned in #107 is still present. Without having internal knowledge about what is going on, I have the gut feeling there is a memory leak, because ofelia will use more and more RAM over time, whenever job have been run.

I am using the latest version available from docker hub.

**Comment by DarkWingMcQuack** [comment]
I set up [mailcow-dockerized](https://github.com/mailcow/mailcow-dockerized) yesterday and today ofelia, which is only used by mailcow-dockerized on my server is using 13 GiB of memory, maybe this is the same problem.

**Comment by ledlamp** [comment]
mine is always using around 200mb, which seems way too much for a job scheduler 😕 
and it just started

**Comment by bkuhl** [comment]
Mine is using 125mb with only 2 schedules defined on a single container:

```
  my-service:
    image: my-image
    command: bash -c "echo \"For log output of cron commands, see the ofelia docker service logs.\" && tail -f /dev/null"
    entrypoint: ""
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.my-app-tool-workflow-timeframe.schedule: "@every 30s"
      ofelia.job-exec.my-app-tool-workflow-timeframe.command: "/opt/entrypoint.sh tool Task1"
      ofelia.job-exec.my-app-tool-queue-scheduled-events.schedule: "@every 30s"
      ofelia.job-exec.my-app-tool-queue-scheduled-events.command: "/opt/entrypoint.sh tool Task2"
```

This does seem quite excessive...
