### ISSUE TITLE
Tasks are getting skipped after a while, and I don't know the reason

### ISSUE THREAD

**Issue by wintercounter** [mcuadros/ofelia#164]
I'm having 3 tasks, after a few days, they start to get skipped with no explanation. I have no clue how can I debug this.

```
2021-10-08T07:21:34.008421091Z 2021-10-08T07:21:34.008Z  common.go:125 ▶ NOTICE [Job "foo" (4726bc31bfd3)] Started - node cron/syncFoo
2021-10-08T07:21:34.008431785Z 2021-10-08T07:21:34.008Z  common.go:123 ▶ WARNING [Job "foo" (4726bc31bfd3)] Finished in "125.16µs", failed: false, skipped: true, error: none
```

```
labels:
            ofelia.enabled: 'true'
            ofelia.job-exec.foo.schedule: '@every 60s'
            ofelia.job-exec.foo.no-overlap: 'true'
            ofelia.job-exec.foo.command: 'node cron/syncFoo'
            ofelia.job-exec.bar.schedule: '@every 60s'
            ofelia.job-exec.bar.no-overlap: 'true'
            ofelia.job-exec.bar.command: 'node cron/syncBar'
            ofelia.job-exec.baz.schedule: '@every 60s'
            ofelia.job-exec.baz.no-overlap: 'true'
            ofelia.job-exec.baz.command: 'node cron/syncBaz'
```

Slowly, all tasks will start to get skipped, but not at the same time, the difference can be several days.
