### ISSUE TITLE
ofelia in docker-mode did not find job-run labels

### ISSUE THREAD

**Issue by jk** [mcuadros/ofelia#167]
I've modified the example from the readme to run a seperate container, like so:

```yml
version: "3.8"

services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nginx
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 30s"
      ofelia.job-local.my-test-job.command: "date"

  nginx:
    image: nginx:latest
    labels:
      ofelia.enabled: "true"
      # job-exec runs
      # ofelia.job-exec.datecron.schedule: "@every 5s"
      # ofelia.job-exec.datecron.command: "date"
      # job-run does not run
      ofeila.job-run.nginx-test.schedule: "@every 5s"
      ofelia.job-run.nginx-test.image: "ubuntu:latest"
      ofelia.job-run.nginx-test.command: "date"

```

But ofelia doesn't seem to find the `job-run` labels:

```
ofelia_1  | 2021-11-29T15:13:03.858Z  scheduler.go:34 ▶ NOTICE New job registered "my-test-job" - "date" - "@every 30s"
ofelia_1  | 2021-11-29T15:13:03.859Z  scheduler.go:54 ▶ DEBUG Starting scheduler with 1 jobs
```

IMO I expect ofelia to pick up the labels annotated in the nginx service, but no. When using the `job-exec` label it does. So I modified the example above to run the `job-run` label on the ofelia service:

```yml
version: "3.8"

services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nginx
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofeila.job-run.ofelia-test.schedule: "@every 5s"
      ofelia.job-run.ofelia-test.image: "ubuntu:latest"
      ofelia.job-run.ofelia-test.command: "date"
```

and I get the following error on starting up ofelia:

```
ofelia-test-ofelia-1  | 2021-11-29T15:20:30.374Z  scheduler.go:34 ▶ NOTICE New job registered "nginx-test" - "ping -c1 localhost" - ""
ofelia-test-ofelia-1  | unable to start a empty scheduler.
```

Looks like ofelia isn't able to interpret `schedule` for `job-run` labels. According to https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md#job-run `job-run` has a mandatory `schedule` field, so this is a bug?
