### ISSUE TITLE
Panic error when labels incorrect

### ISSUE THREAD

**Issue by Triloworld** [mcuadros/ofelia#168]
When testing I get this error.
Ofelia: latest

Container in swarm
```
  ofelia:
    image: mcuadros/ofelia:latest
    networks:
      - proxy
    depends_on:
      - frontend
      - fpm
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.AAA-AAA.schedule: "@every 24h"
      ofelia.job-local.BBB-AAA.command: "date"       
      ofelia.job-local.AAA-AAA-t.schedule: "@every 24h"
      ofelia.job-local.BBB-AAA-t.command: "date"   
```

```
2021-11-30T11:58:21.001Z  common.go:125 ▶ NOTICE [Job "gsitemap-gsitemap-t" (2fa81c97600f)] Started - 

2021/11/30 11:58:21 cron: panic running job: runtime error: index out of range [0] with length 0

goroutine 252 [running]:

github.com/robfig/cron.(*Cron).runWithRecovery.func1()

	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x69

panic({0x8ad640, 0xc000024120})

	/usr/local/go/src/runtime/panic.go:1038 +0x215

github.com/mcuadros/ofelia/core.(*LocalJob).buildCommand(0xc000147400, 0xc000200540)

	/go/src/github.com/mcuadros/ofelia/core/localjob.go:31 +0x285

github.com/mcuadros/ofelia/core.(*LocalJob).Run(0xc000202270, 0x3)

	/go/src/github.com/mcuadros/ofelia/core/localjob.go:21 +0x19

github.com/mcuadros/ofelia/core.(*Context).doNext(0xc000200540)

	/go/src/github.com/mcuadros/ofelia/core/common.go:95 +0xd4

github.com/mcuadros/ofelia/core.(*Context).Next(0xc000200540)

	/go/src/github.com/mcuadros/ofelia/core/common.go:69 +0x1e

github.com/mcuadros/ofelia/core.(*jobWrapper).Run(0xc00000e7b0)

	/go/src/github.com/mcuadros/ofelia/core/scheduler.go:93 +0x1ba

github.com/robfig/cron.(*Cron).runWithRecovery(0x0, {0x9792c0, 0xc00000e7b0})

	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x62

created by github.com/robfig/cron.(*Cron).run

```

Properly code that is corect:
```
      ofelia.job-run.AAA-AAA-t.schedule: "@every 24h"
      ofelia.job-run.AAA-AAA-t.command: "date"   
```

Solution:
Catch error and add some help what is wrong. Right now it isn't helpful.
