### ISSUE TITLE
Error when passing multiple environment variables as label config

### ISSUE THREAD

**Issue by dselivanov** [mcuadros/ofelia#175]
Hi here. Thanks for wonderful software! I'm trying to pass multiple env vars in docker compose using labels and JSON array as suggested in docs:

```yaml
version: '3.4'

services:

  poll-s3:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.poll-s3.schedule: "@every 5s"
      ofelia.job-run.poll-s3.image: "tsc/create-offer:dev"
      ofelia.job-run.poll-s3.environment: ["AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}", "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"]
      ofelia.job-run.poll-s3.command: "poll_s3.py"

```

However I see following error:
> ervices.poll-s3.labels.ofelia.job-run.poll-s3.environment contains ["AWS_ACCESS_KEY_ID=xxxxxx", "AWS_SECRET_ACCESS_KEY=xxxxxx which is an invalid type, it should be a string, number, or a null
