### ISSUE TITLE
Confused on how to use docker compose to schedule an image on swarm

### ISSUE THREAD

**Issue by glenelkinsdev** [mcuadros/ofelia#187]
Hi

The documentation is a bit vague on how to use docker compose in my swarm. I have a specific image i need to use to run my cron jobs in the swarm every minute, but i'm confused on how the docker compose setup works for this.

So there is the ofelia image which i need to run on the swarm as a container to run the schedule, but then i'm not sure how to then tell my php related image to run a command?

So if i have this,

```
gofollow-ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - php-cron
    command: daemon --docker
    labels:
      ofelia.job-service-run.process-video-cron.schedule: "@every 1m"
      ofelia.job-servuce-run.process-video-cron.command: "cd /app && php bin/console processvideo"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

How does it now know to spawn a new container on the swarm using my php image? Say my php service is called "php-cron"

**Comment by maietta** [comment]
Ah yes, one of the many reasons I decided to fork the project. I forgot about this issue in Ofelia. I'd point to it, but pretty busy on project so no time to go digging.

You can try this, adding the following labels to your Ofelia scheduler so it removes this error. Hopefully Ofelia won't complain after that.
```
ofelia:
    image: mcuadros/ofelia:latest
    ...
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 30s"
      ofelia.job-local.my-test-job.command: "date"
...
```

**Comment by glenelkinsdev** [comment]
ok yeh so something isn't right, all i see is it running that my-test-job which is the date one, it's not running my one for the video processing container

**Comment by maietta** [comment]
OMG... yes, My version fixed issue with --docker flag, but forgot to remove that in docs.

Find this line: command: daemon --docker

Remove --docker.

Should just say "command: daemon"

**Comment by glenelkinsdev** [comment]
ok it's running, i'm monitoring it now and see if it runs my command

**Comment by glenelkinsdev** [comment]
it's still not running anything, the log literally isn't showing it even attempting to run my commands. I'm not sure i totally understand how your image knows my cron container exists to pick up the commands? Here is what it looks like:

```
chadburn:
    deploy:
      mode: global
    image: premoweb/chadburn:latest
    restart: always
    depends_on:
      - php-cron
    command: daemon
    labels:
      chadburn.job-local.my-test-job.schedule: "@every 30s"
      chadburn.job-local.my-test-job.command: "date"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - my-net

  php-cron:
    deploy:
      replicas: 2
    restart: always
    image: my-image
    labels:
      chadburn.enabled: "true"
      chadburn.job-service-run.process-video-cron.schedule: "@every 1m"
      chadburn.job-service-run.process-video-cron.command: "cd /usr/share/nginx/html && php bin/console processvideo"
    networks:
      - my-net
```
