### ISSUE TITLE
How to make it work with Docker-Compose ?

### ISSUE THREAD

**Issue by ghostlexly** [mcuadros/ofelia#195]
Hello,

I'am using it today with docker-compose like following : 

`````ini
[job-exec "job-executed-on-running-container"]
schedule = @every 1m
container = message_phpfpm_1
command = php artisan queue:work --tries=3 --max-time=60
`````

message is my project name on docker-compose. How can i call the container with only the container name to be able to use the same file on multiple projects ?

Example of expected ini file:

`````ini
[job-exec "job-executed-on-running-container"]
schedule = @every 1m
container = phpfpm_1
command = php artisan queue:work --tries=3 --max-time=60
`````

**Comment by sqlmiles** [comment]
You can use [labels configuration](https://github.com/mcuadros/ofelia#docker-labels-configurations) instead of ofelia ini config.

**Comment by maietta** [comment]
It's in the readme.

**Comment by ghostlexly** [comment]
Can i do the same with the ini ?
The labels are good but i don't want to have a long list of labels on my docker compose files

**Comment by rishid** [comment]
You could probably mount your ini to `/etc/ofelia/config.ini` inside the container and see if it works

**Comment by antonellopasella** [comment]
I tested mapping  "./ofelia/config.ini:/etc/ofelia/config.ini"  and it won't works.

**Comment by lincolnaleixo** [comment]
Just for further reference, I was able to make it work that way in the volumes:

- ./docker/scheduler:/etc/ofelia

Inside folder docker->scheduler it has config.ini

**Comment by K2ouMais** [comment]
Are you really running the Laravel queue every minute? Why? Is there a reason?

I would understand if you let the scheduler run every minute but not the queue...

**Comment by Tofandel** [comment]
That readme is missing crucial information

If I want to set global config, how to do it with labels is it
```yaml
labels:
            ofelia.slack-webhook: 'https://hooks.slack.com/services/...'
            ofelia.slack-only-on-error: 1
```

Or
```yaml
labels:
            ofelia.global.slack-webhook: 'https://hooks.slack.com/services/...'
            ofelia.global.slack-only-on-error: 1
```

What about the no-overlap, is this correct?

```yaml
            ofelia.job-exec.mailqueue.schedule: "@every 1m"
            ofelia.job-exec.mailqueue.command: "/var/www/html/bin/console swiftmailer:spool:send --mailer=queue --message-limit=30"
            ofelia.job-exec.mailqueue.no-overlap: 1       
  ```
