### ISSUE TITLE
Documentation examples

### ISSUE THREAD

**Issue by makakken** [mcuadros/ofelia#196]
Could you please provide an example in the documentation for some average tasks like:

- I have a Container which should create a tar-Backup file name with y-m-d-backup.tar name `(eg.: mysqldump --no-tablespaces -u my_user -p my_table > /var/backups/$(date +%w)-backup.sql )`. I was not able to find a way how the `$(date +%w)` - part is escaped properly, so it is working like expected.
- I have a container which should create a mysql-backup. The Database user is password secured, i don't want to hardcode the password into the command... whats the proper way to insert the password securely? (eg.: mysqldump --no-tablespaces -u my_user --password=MySecurePassword my_table > /var/backups/$(date +%w)-backup.sql )

Would be nice if anyone could help. I think these where very common tasks, so it would be nice to add it to the documentation-examples...

**Comment by makakken** [comment]
@mcuadros ping! is it really that comlicated? can anyone help please?

**Comment by brlnr23** [comment]
jumping on this - I am facing the same issue and I am running out of ideas ... 
While ` touch /tmp/\`date +%d-%m-%y\`.touchy` works perfectly fine when running it manually via docker exec, it fails via ofelia in docker-compose context. 

```
docker exec -it mycontainer  touch /tmp/`date +%d-%m-%y`.touchy
```
creates a file called `21-04-23.touchy`

with ofelia, it looks like this in docker-compose.yml:
```
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.cron-test.schedule: "@every 30s"
      ofelia.job-exec.cron-test.command: "touch /tmp/`date +%d-%m-%y`.touchy"

```
and the file is called __`date__

I already tried $(date) and $$date but all of these approaches led to the same (wrong) file name.
