### ISSUE TITLE
Multiple jobs in one container via docker compose

### ISSUE THREAD

**Issue by anuzis** [mcuadros/ofelia#206]
The README shows examples of scheduling multiple jobs across different containers via docker compose, but I don't see an example of how to schedule multiple jobs at different frequencies that run within one container. Searched past GitHub Issues & didn't see this addressed. If this is possible, it'd be helpful to see an example added to documentation. Example below is similar to what I have in mind, but it's unclear if ofelia supports this formatting. Appreciate the project & any guidance on how best to handle this.

```
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.my_test_job.schedule: "@daily"
      ofelia.job-exec.my_test_job.command: "python ./manage.py send_scheduled_emails"
      ofelia.job-exec.my_test_job.schedule: "@monthly"
      ofelia.job-exec.my_test_job.command: "python ./manage.py monthly_admin_jobs"
```
