### ISSUE TITLE
Error creating exec: No such container

### ISSUE THREAD

**Issue by gremo** [mcuadros/ofelia#222]
I have a running service `php` described ny `docker-compose.yml` in `httpdocs/app` folder, I can exec commands without issues:

```bash
cd httpdocs/app
root@docker-ubuntu-s-1vcpu-1gb-intel-fra1-01:~/httpdocs/app# docker compose exec php date
Sat May 13 18:37:25 UTC 2023
```

I've added ofelia as service:

```yml
ofelia:
  image: mcuadros/ofelia:latest
  volumes:
    - ./config/docker/ofelia/jobs.ini:/etc/ofelia/config.ini:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
```

`config/docker/ofelia/jobs.ini` content:

```ini
[job-exec "job-executed-on-running-container"]
schedule = @every 10s
container = php
command = date
```

> app-ofelia-1  | 2023-05-13T18:49:28.015Z  common.go:121 ▶ ERROR [Job "job-executed-on-running-container" (9a10f4242d23)] Finished in "10.092525ms", failed: true, skipped: false, error: error creating exec: No such container: php

I may have misunderstood the documentation... should I use the service as docker compos exec? The container id?
