### ISSUE TITLE
docker health check

### ISSUE THREAD

**Issue by willfarrell** [mcuadros/ofelia#23]
include docker health check

https://github.com/docker/go-healthcheck

**Comment by DevDavido** [comment]
Any suggestions for any potential PR on this health check for the daemon? How about adding a command `status` to ofelia?

**Comment by kkovaletp** [comment]
As there is still no healthcheck provided for the docker container (not as part of Dockerfile, and not for docker-compose service definition), here is my own version. Feel free to provide your feedback in the comments and propose better timings or even better ideas for the command.

The idea of this healthcheck command is to at least make sure that the container is alive, the Ofelia binary is functional in general, and the config is fine. I understand that it doesn't check the running Ofelia daemon health. Maybe I'll add some internal job to the Ofelia config and then will monitor the result of that job by healthcheck command in the future, but here is my current version for docker-compose:

```
healthcheck:
      test: /usr/bin/ofelia validate --config=/etc/ofelia/config.ini > /dev/null
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 2m
```

**Comment by michellabbe** [comment]
Not sure why this issue never got any traction, but here's a working internal healthcheck that actually makes sure scheduler is working and also works without a `config.ini` file (e.g. empty ofelia container to use exclusively with labels in other containers).

I replaced the `my-test-job` example (keepalive) job with a `healthcheck` job that writes current date in a temp file every 5 secs.

Then the healthcheck `test` command compares current date with the date in the temp file (also every 5 secs), and reports `healthy` if diff < 5 secs.

```
    labels:
      ofelia.job-local.healthcheck.schedule: "@every 5s"
      ofelia.job-local.healthcheck.command: /bin/sh -c "echo $(date +%s) > /tmp/healthcheck"
    healthcheck:
      test: ["CMD-SHELL", "[ $(( $(date +%s) - $(cat /tmp/healthcheck) )) -le 5 ] || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 10s
```
I usually prefer using iso8601 date format whenever I use timestamps, but in this case sticking with unix date format keeps the test command simpler.

You can change the 5s delay in `schedule`, `test` and `interval` lines to generate less noise in logs.

I personally would like to keep it low and exclude this `healthcheck` local job completely from console logs but I'm not sure if it's possible .
