### ISSUE TITLE
odd job-run behavior - container doesn't have pytz installed / Dockerfile with non root user

### ISSUE THREAD

**Issue by scls19fr** [mcuadros/ofelia#269]
Hello,

I'm using ofelia in a Docker container like so

`docker-compose.yml`

```
services:
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/config.ini:/etc/ofelia.conf
    restart: unless-stopped
```

and `config.ini`

```
; Ofelia configuration file
; see documentation available at
; https://github.com/mcuadros/ofelia
; https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md

[job-run "job_run-ingest_data"]
schedule = @every 10s  ; or @every 5s @hourly or @daily
image = ingest-data-ingest-service
network = myserver-docker_default
```

I have an other service which is pushing data to a server using a CRUD interface (this server is in myserver-docker_default network).

My `ingest-data` directory have the following `docker-compose.yml`

```
services:
  ingest-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSERVER_API_HOST=${MYSERVER_API_HOST}
      - MYSERVER_API_USE_SSL=${MYSERVER_API_USE_SSL}
      - MYSERVER_EMAIL=${MYSERVER_EMAIL}
      - MYSERVER_PASSWORD=${MYSERVER_PASSWORD}
    networks:
      - myserver-docker_default

networks:
  myserver-docker_default:
    external: true
```
`Dockerfile`

```
FROM python:alpine3.19

ARG USER=nonroot
ARG UID=1010
ARG GID=1010
ENV GROUP=${USER}

#RUN apk add --no-cache ...

# Create a non-root user
RUN addgroup -g ${GID} ${GROUP} && \
    adduser -u ${UID} -G $GROUP -D -g "" ${USER}
# Add /home/${USER}/.local/bin
ENV PATH=${PATH}:/home/${USER}/.local/bin
# Change user to a non-root user
USER $USER

RUN pip install --no-cache myserver_api_client pytz

COPY --chown=${USER}:${GROUP} --chmod=500 app.py /home/${USER}/app/app.py

WORKDIR /home/${USER}/app

CMD [ "python", "app.py" ]
#ENTRYPOINT ["python", "app.py"]
```

My app.py script start with

```
#!/usr/bin/env python

import os
import json
import datetime
import pytz
```

I build image like so

    docker compose build --no-cache

I don't understand why `docker compose up ingest-service` works fine
```
[+] Running 1/1
 ✔ Container ingest-data-ingest-service-1  Created                                                                                                                                                          0.1s
Attaching to ingest-service-1
ingest-service-1  | Connecting MYServer @ myserver-api:5000 SSL: False with admin@domain.com
ingest-service-1  | Importing {'TS0': {'2024-04-11T19:08:59.099574+02:00': 0.1}, 'HUM0': {'2024-04-11T19:08:59.099574+02:00': 1.1}}
ingest-service-1  | Import succeeded
ingest-service-1 exited with code 0
```

but when trying to create a new container using this image

```
$ cd ..

docker compose up ofelia
[+] Running 7/0
 ✔ Container myserver-docker-timescaledb-1             Running                                                                                                                                             0.0s
 ✔ Container redis-stack                                Running                                                                                                                                             0.0s
 ✔ Container myserver-docker-wait-for-pg-1             Created                                                                                                                                             0.0s
 ✔ Container myserver-docker-wait-for-redis-1          Created                                                                                                                                             0.0s
 ✔ Container myserver-docker-myserver-api-1           Running                                                                                                                                             0.0s
 ✔ Container myserver-docker-wait-for-myserver-api-1  Created                                                                                                                                             0.0s
 ✔ Container myserver-docker-ofelia-1                  Created                                                                                                                                             0.0s
Attaching to ofelia-1
ofelia-1  | 2024-04-11T17:11:22.124Z  scheduler.go:44 ▶ NOTICE New job registered "job_run-ingest_data" - "" - "@every 10s"
ofelia-1  | 2024-04-11T17:11:22.125Z  scheduler.go:55 ▶ DEBUG Starting scheduler with 1 jobs
ofelia-1  | 2024-04-11T17:11:32.003Z  common.go:125 ▶ NOTICE [Job "job_run-ingest_data" (1ce1184f1ccc)] Started -
ofelia-1  | 2024-04-11T17:11:33.206Z  common.go:125 ▶ NOTICE [Job "job_run-ingest_data" (1ce1184f1ccc)] Found locally image ingest-data-ingest-service
ofelia-1  | 2024-04-11T17:11:34.68Z  common.go:121 ▶ ERROR [Job "job_run-ingest_data" (1ce1184f1ccc)] StdErr: Traceback (most recent call last):
ofelia-1  |   File "/home/nonroot/app/app.py", line 6, in <module>
ofelia-1  |     import pytz
ofelia-1  | ModuleNotFoundError: No module named 'pytz'
ofelia-1  | 2024-04-11T17:11:34.68Z  common.go:121 ▶ ERROR [Job "job_run-ingest_data" (1ce1184f1ccc)] Finished in "2.677058054s", failed: true, skipped: false, error: error non-zero exit code: 1
```

I getting an error about pytz not being installed.. but I thought it was installed because of

    RUN pip install --no-cache myserver_api_client pytz

That's really difficult for me to understand that.

I guess that it's related to the fact I'm using a nonroot user to run and ofelia is probably trying to run image as root.

Any help will be very kind.
