### ISSUE TITLE
job-run example with Docker labels / unable to start a empty scheduler

### ISSUE THREAD

**Issue by scls19fr** [mcuadros/ofelia#270]
Hello,

currently documentation doesn't provide any example of job-run with Docker labels.
 
I only see examples with config.ini.

Is there a way to use labels to use `job-run` ?

But I don't like putting secrets into config.ini (.env is enough!). So what is appropriate solution to manage environment variables with job-run (related issue might be #247)

Kind regards

**Comment by kopf** [comment]
This is supported. just use labels that begin with, unsurprisingly, `ofelia.job-run.`

**Comment by scls19fr** [comment]
Well but do you have to also put something into `config.ini` or labels on scheduled services are enough ?

Because I tried with an docker-compose like so

```yaml
services:
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/config.ini:/etc/ofelia.conf
    restart: unless-stopped

  ingest-service:
    build: 
      context: ingest-data
      dockerfile: Dockerfile
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.ingest-service.schedule: "@every 5s"
    environment:
      - MYSERVER_API_HOST=${MYSERVER_API_HOST}
      - MYSERVER_API_USE_SSL=${MYSERVER_API_USE_SSL}
      - MYSERVER_EMAIL=${MYSERVER_EMAIL}
      - MYSERVER_PASSWORD=${MYSERVER_PASSWORD}
```

and I get

```
docker compose up ofelia
Attaching to ofelia-1
ofelia-1  | unable to start a empty scheduler.
ofelia-1 exited with code 0
```

**Comment by kopf** [comment]
@scls19fr - 

```
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.ingest-service.schedule: "@every 5s"
```

You've defined the schedule for a job, but haven't defined the job. You need to tell ofelia what to run. Refer to the documentation again.

**Comment by scls19fr** [comment]
I'm using job-run, no job-exec that's a typo

**Comment by scls19fr** [comment]
is `command` necessary? can't we use ENTRYPOINT from Dockerfile?

**Comment by scls19fr** [comment]
My docker-compose now looks like

```
services:  
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/config.ini:/etc/ofelia.conf
    restart: unless-stopped

  ingest-service:
    build: 
      context: ingest-data
      dockerfile: Dockerfile
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.ingest-service.schedule: "@every 5s"
      ofelia.job-run.my-ingest-service.command: "python ./app.py"
    environment:
      - MYSERVER_API_HOST=${MYSERVER_API_HOST}
      - MYSERVER_API_USE_SSL=${MYSERVER_API_USE_SSL}
      - MYSERVER_EMAIL=${MYSERVER_EMAIL}
      - MYSERVER_PASSWORD=${MYSERVER_PASSWORD}
```

but I tried

    $ docker compose build ingest-service
    $ docker compose up ofelia

and I'm still getting `unable to start a empty scheduler.`
