### ISSUE TITLE
Job Run Give Container a Name?

### ISSUE THREAD

**Issue by isaacrlevin** [mcuadros/ofelia#290]
Maybe I am not seeing it in the docs for `job-run` but using labels how can I give the container a specific name? I assume I would need to use `no-overlap` for this but curious if that is something I can do using labels.

For reference something like this

```yml
      ofelia.job-run.polling-ffmpeg.name: "process-videos" <--------- I would like this
      ofelia.job-run.polling-ffmpeg.schedule: "@daily"
      ofelia.job-run.polling-ffmpeg.image: "ffmpeg"
      ofelia.job-run.polling-ffmpeg.no-overlap: "true"
      ofelia.job-run.polling-ffmpeg.delete: "true"
      ofelia.job-run.polling-ffmpeg.volume: "/mnt/data/Downloads/:/Downloads:rw"
      ofelia.job-run.polling-ffmpeg.command: "./run-ffmpeg.sh"
```
