### ISSUE TITLE
Capturing the output of a job-exec using Docker labels?

### ISSUE THREAD

**Issue by gremo** [mcuadros/ofelia#306]
Using Docker labels:

```yaml
labels:
    ofelia.enabled: "true"
    ofelia.job-exec.backup-db.schedule: "@every 15s"
    ofelia.job-exec.backup-db.command: "echo 'hello' > foo.sql"
```

I'd like to capture the output of the command (i.e. `mysqldump` command)). I find hard to understand where foo.sql is placed?
