### ISSUE TITLE
Version 0.4.0-beta can not register jobs any longer

### ISSUE THREAD

**Issue by jurgenhaas** [mcuadros/ofelia#351]
The error message in docker logs is this:

```
cron-1  | 2025-05-04T09:06:09.83+02:00  scheduler.go:40 ▶ WARNING  Failed to register job "Reset Drupal cache" - "sh -c \"cd /var/www/html && /var/www/html/vendor/bin/drush -y cr && curl -fsS --retry 5 --retry-delay 9 -o /dev/null https://healthchecks.example.com/ping/uuid\"" - "0 40 0 * * *"
```

The docker compose service is defined like this:

```
  cron:
    image: 'mcuadros/ofelia:latest'
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /drupal/577/main/app/crontabs/jobs.ini:/etc/ofelia/config.ini
```

The config file contains this:

```
[job-exec "Reset Drupal cache"]
no-overlap = true
tty = true
user = www-data
schedule = 0 40 0 * * *
container = drupal_lauth_main-php-1
command = sh -c \"cd /var/www/html && /var/www/html/vendor/bin/drush -y cr && curl -fsS --retry 5 --retry-delay 9 -o /dev/null https://healthchecks.example.com/ping/uuid\"
```

This worked for years up to the latest version before this beta. I checked the docs and the issues but I could find any breaking change. ANy idea what's going wrong?
