### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by aboussofara** [mcuadros/ofelia#44]
For any command I'm trying to do (curl, touch, echo ... ie ). I got the following message "executable file not found in $PATH "

**Comment by sergio-rivas** [comment]
I get the same error on everything.

**Comment by samvdb** [comment]
same, slack webhooks dont work also.

x509: failed to load system roots and no roots provided"

**Comment by mailtosmyk** [comment]
Useless until fixed:
2018/09/26 02:12:00 scheduler.go:100 ▶ DEBUG job-executed-on-current-host - Job started "8fd00b3db66d" - "ls /var/log"
2018/09/26 02:12:00 scheduler.go:120 ▶ ERROR job-executed-on-current-host - Job finished "8fd00b3db66d" in "320.113µs", failed: true, skipped: false, error: exec: "ls": executable file not found in $PATH

**Comment by lazyfrosch** [comment]
Guys the default container here is a minimal go binary, there is no other tool other than ofelia inside the container...

**Comment by demudrol** [comment]
> Guys the default container here is a minimal go binary, there is no other tool other than ofelia inside the container...

but in README job-local: runs the command inside of the host running ofelia, not in container

**Comment by starspoint** [comment]
Anybody found the solution or a sample use case for job-local?

**Comment by lhilton** [comment]
Another +1 on this, doesn't seem to be working in any kind of fashion.

Logs:

`2018/12/13 19:49:03 scheduler.go:34 ▶ NOTICE New job registered "job-executed-on-running-container" - "touch /tmp/example" - "@every 1m"
2018/12/13 19:49:03 scheduler.go:54 ▶ DEBUG Starting scheduler with 1 jobs
2018/12/13 19:50:03 scheduler.go:100 ▶ DEBUG job-executed-on-running-container - Job started "60675ac91789" - "touch /tmp/example"
2018/12/13 19:50:03 scheduler.go:120 ▶ ERROR job-executed-on-running-container - Job finished "60675ac91789" in "135.702µs", failed: true, skipped: false, error: exec: "touch": executable file not found in $PATH`

My config:

`[job-local "job-executed-on-running-container"]
schedule = @every 1m
no-overlap = true
command = touch /tmp/example`

**Comment by robot110011** [comment]
Anyone found a solution to this or another scheduler that doesn't have this error?

**Comment by mikida12** [comment]
anything new about this issue?

**Comment by c0ze** [comment]
For slack webhooks, check

https://github.com/mcuadros/ofelia/issues/51

For other stuff not working on ofelia container, it is expected. I am not sure why you need to do this. If you are simply following the README, forget about it, just run it on another container which has these tools `touch` `echo` etc.

If you need to run these on the ofelia container, you need to create a new container using ofelia as base, and add whatever stuff you need.

**Comment by Trane9991** [comment]
Closed due to age. Reopen if needed.

**Comment by Triloworld** [comment]
Solution for future reference:
```
  ofelia:
    image: mcuadros/ofelia:latest
    networks:
      - proxy
    depends_on:
      - frontend
      - fpm
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.frontend.schedule: "@every 24h"
      ofelia.job-run.frontend.image: "curlimages/curl:7.80.0"
      ofelia.job-run.frontend.command: "--silent -H 'Cache-Control: no-cache' -L 'https://domain.com/...'"   
```

Consider local as test option and health check rather than production case scenario
