### ISSUE TITLE
Hot reload of the config

### ISSUE THREAD

**Issue by mcuadros** [mcuadros/ofelia#5]
Using inotify or maybe with a signal, allow to reload the configuration without the requirement of restart the process

**Comment by juanjux** [comment]
HUP is the standar Unix signal for "reload config".

**Comment by mcuadros** [comment]
BTW this is already implemented, but not very tested, so this is the reason because I didn't closed the issue

**Comment by timgriffiths** [comment]
@mcuadros how do i go about testing this?

**Comment by mbtamuli** [comment]
> BTW this is already implemented

@mcuadros Can you please describe how to test hot reloading?

**Comment by Gaibhne** [comment]
Has this been in testing since 2017 ? Or was the feature abandoned ? Reloading config would be a huge advantage in order to not lose job state (such as jobs with @every scheduling not all restarting from scratch when you restart the container).

**Comment by escoand** [comment]
This is working fine for me when called manually with `docker exec -it ofelia killall -HUP ofelia`. But I had problems when called by a exec job:

```yaml
version: "2.4"
services:
  ofelia:
    container_name: ofelia
    image: mcuadros/ofelia
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.reload_config.schedule: "@daily"
      ofelia.job-exec.reload_config.command: killall -HUP ofelia
```

```
2021-12-16T07:41:50.044Z  common.go:125 ▶ NOTICE [Job "reload_config" (48efe0168ed5)] Started - killall -HUP ofelia
2021-12-16T07:41:50.409Z  common.go:121 ▶ ERROR [Job "reload_config" (48efe0168ed5)] Finished in "17.295737ms", failed: true, skipped: false, error: error creating exec: No such container: 
```

What is wrong here?
