### ISSUE TITLE
configure with docker labels

### ISSUE THREAD

**Issue by mathroc** [mcuadros/ofelia#57]
It would be nice to discover jobs looking at container and services tags (à la traefik)

eg, in a docker-compose file :

```yaml
labels:
  - ofelia.schedule: "@hourly"
  - ofelia.command: "touch /tmp/example"
```

it could support `job-exec` and `job-service-run` (once #49 is merged) or maybe a `job-service-exec` style

this would make it much easier to work with as you wouldn't have to give access to the container running ofelia or its configuration to the user running app containers or stacks

the idea come from traefik and https://github.com/vfarcic/docker-flow-cron but this project is not ready nor very active
