### ISSUE TITLE
no-overlap in docker-compose with labels

### ISSUE THREAD

**Issue by AntonFriberg** [mcuadros/ofelia#76]
Hi!

How do I use `no-overlap` with labels?

This is my current setup.

```yaml
version: '3'
services:
  scheduler:
    image: mcuadros/ofelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "date"
    command: ["daemon", "--docker"]

  test:
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - scheduler
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.sleep-test.no-overlap: "true"
      ofelia.job-exec.sleep-test.schedule: "@every 10s"
      ofelia.job-exec.sleep-test.command: "sleep 60"
```

This is the result I get. As you can see multiple concurrent jobs are executed.

```
$ docker-compose up
latest: Pulling from library/ubuntu
7ddbc47eeb70: Pull complete
c1bbdc448b72: Pull complete
8c3b70e39044: Pull complete
45d437916d57: Pull complete
Digest: sha256:6e9f67fa63b0323e9a1e587fd71c561ba48a034504fb804fd26fd8800039835d
Status: Downloaded newer image for ubuntu:latest
Recreating ofelia-scheduler ... done
Creating ofelia_test_1 ... done
Attaching to ofelia_scheduler_1, ofelia_test_1
scheduler_1  | scheduler.go:35 ▶ NOTICE New job registered "run-data-transfer" - "sleep 60" - "@every 10s"
scheduler_1  | scheduler.go:35 ▶ NOTICE New job registered "my-test-job" - "date" - "@every 5s"
scheduler_1  | scheduler.go:55 ▶ DEBUG Starting scheduler with 2 jobs
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (0bc42ab0f6d4)] Started - date
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (0bc42ab0f6d4)] Output: Tue Nov  5 15:35:25 UTC 2019
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (0bc42ab0f6d4)] Finished in "2.055488ms", failed: false, skipped: false, error: none
scheduler_1  | common.go:121 ▶ NOTICE [Job "run-data-transfer" (f4f327a06727)] Started - sleep 60
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (26a5c2ad7aaa)] Started - date
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (26a5c2ad7aaa)] Output: Tue Nov  5 15:35:30 UTC 2019
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (26a5c2ad7aaa)] Finished in "2.407151ms", failed: false, skipped: false, error: none
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (da566bd03f19)] Started - date
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (da566bd03f19)] Output: Tue Nov  5 15:35:35 UTC 2019
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (da566bd03f19)] Finished in "1.982562ms", failed: false, skipped: false, error: none
scheduler_1  | common.go:121 ▶ NOTICE [Job "run-data-transfer" (08c9fb6824b5)] Started - sleep 60
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (a9aff874c444)] Started - date
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (a9aff874c444)] Output: Tue Nov  5 15:35:40 UTC 2019
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (a9aff874c444)] Finished in "2.086044ms", failed: false, skipped: false, error: none
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (7e6b5a3cccf3)] Started - date
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (7e6b5a3cccf3)] Output: Tue Nov  5 15:35:45 UTC 2019
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (7e6b5a3cccf3)] Finished in "2.121731ms", failed: false, skipped: false, error: none
scheduler_1  | common.go:121 ▶ NOTICE [Job "run-data-transfer" (2940e466689f)] Started - sleep 60
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (2568f2bf08f4)] Started - date
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (2568f2bf08f4)] Output: Tue Nov  5 15:35:50 UTC 2019
scheduler_1  | common.go:121 ▶ NOTICE [Job "my-test-job" (2568f2bf08f4)] Finished in "7.36214ms", failed: false, skipped: false, error: none
```
