### ISSUE TITLE
Scheduler not discovering docker-compose container based on labels

### ISSUE THREAD

**Issue by ashleysommer** [mcuadros/ofelia#78]
Here's my minimal reproduction of the docker-compose file:
```
version: "3"
services:

  scheduler:
    image: mcuadros/ofelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      ofelia.job-local.my-test-job.schedule: "@daily"
      ofelia.job-local.my-test-job.command: "echo 'still running'"
    command: ["daemon", "--docker"]

  test_schedule:
    image: alpine:3.9
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - scheduler
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.test-job1.schedule: "@every 5s"
      ofelia.job-exec.test-job1.command: "/bin/sh -c 'echo hello'"
```

Here is the output:
```
$> docker-compose  up                                                                                                                                               
Recreating docker_scheduler_1 ... done
Creating docker_test_schedule_1 ... done
Attaching to docker_scheduler_1, docker_test_schedule_1
scheduler_1      | scheduler.go:35 ▶ NOTICE New job registered "my-test-job" - "echo 'still running'" - "@daily"
scheduler_1      | scheduler.go:55 ▶ DEBUG Starting scheduler with 1 jobs
```

As you can see, the scheduler only registers the one job-local configuration, it does not discover the one from my second container.

I've based the config on the docker-compose file I saw in [this issue: #76](https://github.com/mcuadros/ofelia/issues/76), it seems to work fine, the output in the text in that issue shows two jobs registered.
