### ISSUE TITLE
docker compose help

### ISSUE THREAD

**Issue by rafipiccolo** [mcuadros/ofelia#99]
hello,

I use the default config from the readme, but i thinks it doesn't work.

here is my docker compose with 2 services :
```
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # a container that shows date every second
  # with a cron that also shows date every second
  datelogger:
    image: busybox
    container_name: datelogger
    command: sh -c "while true; do $$(echo date); sleep 1; done"
    restart: always
    labels:
      - ofelia.enabled=true
      - ofelia.job-exec.datecron.schedule="@every 1s"
      - ofelia.job-exec.datecron.command="date"
```

i've heard that ofelia is not listening to docker events so i need to start them in order. So i do :
docker-compose up -d datelogger
docker-compose up -d ofelia

then i look at logs of datelogger => OK
bug, logs of ofelia seems buggy, here is an extract :

```
today at 10:41 AM scheduler.go:35 ▶ NOTICE New job registered "datecron" - "\"date\"" - "\"@every 1s\""
today at 10:41 AM unable to start a empty scheduler.
today at 10:42 AM scheduler.go:35 ▶ NOTICE New job registered "datecron" - "\"date\"" - "\"@every 1s\""
today at 10:42 AM unable to start a empty scheduler.
today at 10:43 AM scheduler.go:35 ▶ NOTICE New job registered "datecron" - "\"date\"" - "\"@every 1s\""
today at 10:43 AM unable to start a empty scheduler.
```

Why do i see a new job registration every minute. Is it because ofelia is reading labels every minutes ? it means that i dont need to restart ofelia when i start new container with labels ?

thanks for your help.

**Comment by Trane9991** [comment]
Hey @rafipiccolo,
I was able to reproduce the problem locally. There is some problem with docker-compose labels format and extra quotes, you see in the log here: `"\"date\""`.

So I tried different labels formats and here is the result:

1. Key/value based labels - **works fine**
```yaml
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 5s"
      ofelia.job-exec.datecron.command: "date"
```

2. List-based labels with quotes - **doesn't work**:
```yaml
    labels:
      - ofelia.enabled="true"
      - ofelia.job-exec.datecron.schedule="@every 5s"
      - ofelia.job-exec.datecron.command="date
```

2. List-based labels without quotes - **works fine**:
```yaml
    labels:
      - ofelia.enabled=true
      - ofelia.job-exec.datecron.schedule=@every 5s
      - ofelia.job-exec.datecron.command=date
```

Regarding the:
> Why do i see a new job registration every minute. Is it because ofelia is reading labels every minutes ? it means that i dont need to restart ofelia when i start new container with labels ?

This is because Ofelia actually exits after the message `unable to start a empty scheduler` and `restart: always` kicks in, restarting it over and over again, this why you see that recurring message. A no, Ofelia currently doesn't refresh labels on the go and need to be restarted.

Also, in order to start containers in proper order, you can add `depends_on` parameter.
Complete docker-compose.yaml:
```yaml
version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - datelogger
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # a container that shows date every second
  # with a cron that also shows date every second
  datelogger:
    image: busybox
    container_name: datelogger
    command: sh -c "while true; do $$(echo date); sleep 1; done"
    restart: always
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 1s"
      ofelia.job-exec.datecron.command: "date"
```

**Comment by rafipiccolo** [comment]
thanks it works :)

**Comment by Trane9991** [comment]
I think this is related to how labels being passed by docker-compose.

So when the label is set as `ofelia.job-exec.datecron.schedule: "@every 5s"` then it is a key/value and value need be quoted, but when it is string like `ofelia.job-exec.datecron.schedule=@every 5s` it is already a string, that will be splitter by the `=` doesn't need to be quoted, because in this case, quotes considered as part of the value.

So I'm not sure if there is anything to be fixed in the code, but I would add an basic `docker-compose` example, so other people have a place where to start.

Thanks for the issue.

**Comment by Trane9991** [comment]
Done 7cad21014cb8217f0ae9a911b61ba100fea5f84d :)

**Comment by eduardofb** [comment]
Hi, @Trane9991. I'm getting the same error, but when running with the `job-run` label. What I understand is Ofelia should create a new container, and run the command.

Any thoughts?

```
version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nginx
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  nginx:
    image: nginx
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.datecron.schedule: "@every 5s"
      ofelia.job-run.datecron.command: "uname -a"
```

**Comment by Trane9991** [comment]
Hey @eduardofb
only `job-exec` need to be specified as labels to the *target* containers because ofelia will need to `exec` into that container.

Since you need a `job-run` and it will create *new* container, you need to configure it as labels for the `ofelia` container itself, plus specify image to run, for example:

```yaml
version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.datecron.schedule: "@every 5s"
      ofelia.job-run.datecron.command: "sleep 10"
      ofelia.job-run.datecron.image: "nginx:latest"
```

if you run `docker ps` after 5 sec, you will see `nginx` container started.
However, what I just noticed is that output from the `job-run` container is not being captured/logged, not sure why is that... Will need to check.
